language: swift
osx_image: xcode10.2
before_install:
  - HOMEBREW_NO_INSTALL_CLEANUP=1 brew install yarn
install:
  - carthage update --platform macos --cache-builds
  - yarn install
script:
  - yarn build:script
  - set -o pipefail && xcodebuild clean build -scheme Polyglot CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO | xcpretty
cache:
  directories:
  - Carthage