name: Polyglot
on: [push]
jobs:
  build:
    name: Test Build
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-node@master
      - run: yarn install
      - run: yarn build
      - run: set -o pipefail && xcodebuild build -scheme Polyglot CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO | xcpretty
